//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RunCat365.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class UserSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static UserSettings defaultInstance = ((UserSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new UserSettings())));
        
        public static UserSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cat")]
        public string Runner {
            get {
                return ((string)(this["Runner"]));
            }
            set {
                this["Runner"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Theme {
            get {
                return ((string)(this["Theme"]));
            }
            set {
                this["Theme"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TemperatureUnit {
            get {
                return ((string)(this["TemperatureUnit"]));
            }
            set {
                this["TemperatureUnit"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FPS40")]
        public string FPSMaxLimit {
            get {
                return ((string)(this["FPSMaxLimit"]));
            }
            set {
                this["FPSMaxLimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FirstLaunch {
            get {
                return ((bool)(this["FirstLaunch"]));
            }
            set {
                this["FirstLaunch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int HighScore {
            get {
                return ((int)(this["HighScore"]));
            }
            set {
                this["HighScore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CPU")]
        public string SpeedSource {
            get {
                return ((string)(this["SpeedSource"]));
            }
            set {
                this["SpeedSource"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CustomRunnerName {
            get {
                return ((string)(this["CustomRunnerName"]));
            }
            set {
                this["CustomRunnerName"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CpuIndicatorEnabled {
            get {
                return ((bool)(this["CpuIndicatorEnabled"]));
            }
            set {
                this["CpuIndicatorEnabled"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cat")]
        public string CpuRunner {
            get {
                return ((string)(this["CpuRunner"]));
            }
            set {
                this["CpuRunner"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CpuCustomRunnerName {
            get {
                return ((string)(this["CpuCustomRunnerName"]));
            }
            set {
                this["CpuCustomRunnerName"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GpuIndicatorEnabled {
            get {
                return ((bool)(this["GpuIndicatorEnabled"]));
            }
            set {
                this["GpuIndicatorEnabled"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Parrot")]
        public string GpuRunner {
            get {
                return ((string)(this["GpuRunner"]));
            }
            set {
                this["GpuRunner"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GpuCustomRunnerName {
            get {
                return ((string)(this["GpuCustomRunnerName"]));
            }
            set {
                this["GpuCustomRunnerName"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MemoryIndicatorEnabled {
            get {
                return ((bool)(this["MemoryIndicatorEnabled"]));
            }
            set {
                this["MemoryIndicatorEnabled"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Horse")]
        public string MemoryRunner {
            get {
                return ((string)(this["MemoryRunner"]));
            }
            set {
                this["MemoryRunner"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MemoryCustomRunnerName {
            get {
                return ((string)(this["MemoryCustomRunnerName"]));
            }
            set {
                this["MemoryCustomRunnerName"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TemperatureIndicatorEnabled {
            get {
                return ((bool)(this["TemperatureIndicatorEnabled"]));
            }
            set {
                this["TemperatureIndicatorEnabled"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cat")]
        public string TemperatureRunner {
            get {
                return ((string)(this["TemperatureRunner"]));
            }
            set {
                this["TemperatureRunner"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TemperatureCustomRunnerName {
            get {
                return ((string)(this["TemperatureCustomRunnerName"]));
            }
            set {
                this["TemperatureCustomRunnerName"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CpuColorTintEnabled {
            get {
                return ((bool)(this["CpuColorTintEnabled"]));
            }
            set {
                this["CpuColorTintEnabled"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CpuRunnerSpeedEnabled {
            get {
                return ((bool)(this["CpuRunnerSpeedEnabled"]));
            }
            set {
                this["CpuRunnerSpeedEnabled"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GpuColorTintEnabled {
            get {
                return ((bool)(this["GpuColorTintEnabled"]));
            }
            set {
                this["GpuColorTintEnabled"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GpuRunnerSpeedEnabled {
            get {
                return ((bool)(this["GpuRunnerSpeedEnabled"]));
            }
            set {
                this["GpuRunnerSpeedEnabled"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MemoryColorTintEnabled {
            get {
                return ((bool)(this["MemoryColorTintEnabled"]));
            }
            set {
                this["MemoryColorTintEnabled"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MemoryRunnerSpeedEnabled {
            get {
                return ((bool)(this["MemoryRunnerSpeedEnabled"]));
            }
            set {
                this["MemoryRunnerSpeedEnabled"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TemperatureColorTintEnabled {
            get {
                return ((bool)(this["TemperatureColorTintEnabled"]));
            }
            set {
                this["TemperatureColorTintEnabled"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TemperatureRunnerSpeedEnabled {
            get {
                return ((bool)(this["TemperatureRunnerSpeedEnabled"]));
            }
            set {
                this["TemperatureRunnerSpeedEnabled"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int CpuColorTintStrength {
            get {
                return ((int)(this["CpuColorTintStrength"]));
            }
            set {
                this["CpuColorTintStrength"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int GpuColorTintStrength {
            get {
                return ((int)(this["GpuColorTintStrength"]));
            }
            set {
                this["GpuColorTintStrength"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int MemoryColorTintStrength {
            get {
                return ((int)(this["MemoryColorTintStrength"]));
            }
            set {
                this["MemoryColorTintStrength"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int TemperatureColorTintStrength {
            get {
                return ((int)(this["TemperatureColorTintStrength"]));
            }
            set {
                this["TemperatureColorTintStrength"] = value;
            }
        }


        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CpuStillModeEnabled {
            get {
                return ((bool)(this["CpuStillModeEnabled"]));
            }
            set {
                this["CpuStillModeEnabled"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CpuStillSetName {
            get {
                return ((string)(this["CpuStillSetName"]));
            }
            set {
                this["CpuStillSetName"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GpuStillModeEnabled {
            get {
                return ((bool)(this["GpuStillModeEnabled"]));
            }
            set {
                this["GpuStillModeEnabled"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GpuStillSetName {
            get {
                return ((string)(this["GpuStillSetName"]));
            }
            set {
                this["GpuStillSetName"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MemoryStillModeEnabled {
            get {
                return ((bool)(this["MemoryStillModeEnabled"]));
            }
            set {
                this["MemoryStillModeEnabled"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MemoryStillSetName {
            get {
                return ((string)(this["MemoryStillSetName"]));
            }
            set {
                this["MemoryStillSetName"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TemperatureStillModeEnabled {
            get {
                return ((bool)(this["TemperatureStillModeEnabled"]));
            }
            set {
                this["TemperatureStillModeEnabled"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TemperatureStillSetName {
            get {
                return ((string)(this["TemperatureStillSetName"]));
            }
            set {
                this["TemperatureStillSetName"] = value;
            }
        }

        public bool IndicatorsMigrated {
            get {
                return ((bool)(this["IndicatorsMigrated"]));
            }
            set {
                this["IndicatorsMigrated"] = value;
            }
        }
    }
}
